<?php

namespace tapasBundle\Repository;

/**
 * TapasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TapasRepository extends \Doctrine\ORM\EntityRepository
{
}
