cliente:
    resource: "@ClienteBundle/Controller/"
    type:     annotation
    prefix:   /cliente/

tapas:
    resource: "@tapasBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
